root: true
env:
  browser: true
  es6: true
extends:
  - plugin:react/recommended
  - standard
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
rules:
  indent:
    - error
    - 2
  limited-exports-page-templates: warn
  no-anonymous-exports-page-templates: warn
  react/function-component-definition:
    - error
    - namedComponents: arrow-function
      unnamedComponents: arrow-function
  react/jsx-tag-spacing:
    - error
    - closingSlash: never
      beforeSelfClosing: never
      afterOpening: never
      beforeClosing: never
  react/no-unescaped-entities: off
  react/react-in-jsx-scope: off
settings:
  react:
    version: detect
